<a href="https://colab.research.google.com/github/kavitharv98-png/DEEP-LEARNING/blob/main/CNN_feature_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
I = np.array([
    [1, 4, 7, 1, 6],
    [2, 5, 8, 2, 7],
    [3, 6, 9, 3, 8],
    [0, 1, 2, 4, 9],
    [1, 2, 3, 5, 0]
])

K = np.array([
    [1, 1, 1],
    [0, 0, 0],
    [1, 1, 1]
])
stride = 1
input_rows, input_cols = I.shape
kernel_rows, kernel_cols = K.shape
padding = 0
output_rows = (input_rows - kernel_rows + 2 * padding) // stride + 1
output_cols = (input_cols - kernel_cols + 2 * padding) // stride + 1
output = np.zeros((output_rows, output_cols))

for i in range(output_rows):
    for j in range(output_cols):


        region = I[
            i * stride : i * stride + kernel_rows,
            j * stride : j * stride + kernel_cols
        ]

        output[i, j] = np.sum(region * K)

print("Output Feature Map after Convolution:")
print(output)
relu_output = np.maximum(0, output)
print("\nOutput Feature Map after ReLU:")
print(relu_output)

Output Feature Map after Convolution:
[[30. 30. 34.]
 [18. 22. 32.]
 [24. 28. 28.]]

Output Feature Map after ReLU:
[[30. 30. 34.]
 [18. 22. 32.]
 [24. 28. 28.]]
